apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "i6o-blog.fullname" . }}-env
  labels:
    {{- include "i6o-blog.labels" . | nindent 4 }}
data:
  .env.production: |
    REDIS_URL=redis://{{ template "common.names.fullname" .Subcharts.redis }}-master:6379